In [1]:
import pandas as pd
import numpy as np

In [7]:
data_generator = lambda: np.array([np.random.rand(12), np.random.randint(1, 10, 12), np.random.randint(20, 30, 12)]).transpose()

In [8]:
sample = np.array([data_generator() for _ in range(4)])

In [9]:
sample.shape

(4, 12, 3)

## 4个样本， 12个月， 3个feature

In [10]:
sample

array([[[  8.70153823e-01,   9.00000000e+00,   2.40000000e+01],
        [  6.56261111e-01,   1.00000000e+00,   2.70000000e+01],
        [  2.97759126e-01,   6.00000000e+00,   2.10000000e+01],
        [  6.93777475e-01,   5.00000000e+00,   2.70000000e+01],
        [  9.39944542e-01,   4.00000000e+00,   2.40000000e+01],
        [  8.76681573e-01,   2.00000000e+00,   2.10000000e+01],
        [  9.63210105e-01,   3.00000000e+00,   2.60000000e+01],
        [  7.69305632e-01,   6.00000000e+00,   2.50000000e+01],
        [  4.40866524e-01,   9.00000000e+00,   2.60000000e+01],
        [  9.29054200e-01,   4.00000000e+00,   2.50000000e+01],
        [  3.39889678e-02,   6.00000000e+00,   2.90000000e+01],
        [  9.27163829e-01,   1.00000000e+00,   2.70000000e+01]],

       [[  2.19388973e-01,   7.00000000e+00,   2.40000000e+01],
        [  6.13667589e-01,   4.00000000e+00,   2.50000000e+01],
        [  8.78040763e-02,   7.00000000e+00,   2.10000000e+01],
        [  9.95796173e-01,   7.00000000e+00,   2.00000000e+01],
        [  7.71184377e-01,   6.00000000e+00,   2.00000000e+01],
        [  5.34012613e-01,   3.00000000e+00,   2.60000000e+01],
        [  8.31464842e-01,   3.00000000e+00,   2.00000000e+01],
        [  8.63216046e-01,   6.00000000e+00,   2.70000000e+01],
        [  6.83494194e-01,   5.00000000e+00,   2.00000000e+01],
        [  9.95828258e-01,   5.00000000e+00,   2.70000000e+01],
        [  4.31960738e-01,   1.00000000e+00,   2.40000000e+01],
        [  5.79195170e-03,   7.00000000e+00,   2.20000000e+01]],

       [[  2.19878139e-01,   4.00000000e+00,   2.60000000e+01],
        [  2.97455223e-01,   7.00000000e+00,   2.40000000e+01],
        [  6.47589038e-01,   8.00000000e+00,   2.80000000e+01],
        [  9.72401368e-01,   9.00000000e+00,   2.20000000e+01],
        [  6.09236386e-01,   9.00000000e+00,   2.80000000e+01],
        [  4.14977282e-01,   4.00000000e+00,   2.20000000e+01],
        [  2.72910417e-01,   1.00000000e+00,   2.40000000e+01],
        [  2.34229788e-01,   1.00000000e+00,   2.50000000e+01],
        [  1.47174558e-01,   2.00000000e+00,   2.80000000e+01],
        [  1.02641232e-01,   1.00000000e+00,   2.80000000e+01],
        [  3.16599065e-01,   5.00000000e+00,   2.00000000e+01],
        [  4.20905210e-01,   8.00000000e+00,   2.00000000e+01]],

       [[  8.65145386e-01,   5.00000000e+00,   2.80000000e+01],
        [  4.80571294e-01,   3.00000000e+00,   2.50000000e+01],
        [  2.75607710e-01,   9.00000000e+00,   2.40000000e+01],
        [  3.85028502e-01,   9.00000000e+00,   2.80000000e+01],
        [  2.29358937e-01,   1.00000000e+00,   2.00000000e+01],
        [  3.98262853e-01,   8.00000000e+00,   2.20000000e+01],
        [  5.16400644e-01,   4.00000000e+00,   2.00000000e+01],
        [  9.38618452e-01,   9.00000000e+00,   2.90000000e+01],
        [  4.71717132e-01,   8.00000000e+00,   2.80000000e+01],
        [  6.29519839e-01,   3.00000000e+00,   2.80000000e+01],
        [  7.59610046e-01,   2.00000000e+00,   2.00000000e+01],
        [  4.15093122e-02,   5.00000000e+00,   2.00000000e+01]]])

# 层次索引之后，每个listing的每个月的第一个feature的值

In [15]:
pd.DataFrame(sample[:,:,0]).stack()

0  0     0.870154
   1     0.656261
   2     0.297759
   3     0.693777
   4     0.939945
   5     0.876682
   6     0.963210
   7     0.769306
   8     0.440867
   9     0.929054
   10    0.033989
   11    0.927164
1  0     0.219389
   1     0.613668
   2     0.087804
   3     0.995796
   4     0.771184
   5     0.534013
   6     0.831465
   7     0.863216
   8     0.683494
   9     0.995828
   10    0.431961
   11    0.005792
2  0     0.219878
   1     0.297455
   2     0.647589
   3     0.972401
   4     0.609236
   5     0.414977
   6     0.272910
   7     0.234230
   8     0.147175
   9     0.102641
   10    0.316599
   11    0.420905
3  0     0.865145
   1     0.480571
   2     0.275608
   3     0.385029
   4     0.229359
   5     0.398263
   6     0.516401
   7     0.938618
   8     0.471717
   9     0.629520
   10    0.759610
   11    0.041509
dtype: float64

# 以此类推

In [16]:
columns = ['feature1', 'feature2', 'feature3']
df = pd.DataFrame({columns[i]: pd.DataFrame(sample[:,:,i]).stack() for i in range(len(columns))})

In [18]:
df

      feature1  feature2  feature3
0 0   0.870154       9.0      24.0
  1   0.656261       1.0      27.0
  2   0.297759       6.0      21.0
  3   0.693777       5.0      27.0
  4   0.939945       4.0      24.0
  5   0.876682       2.0      21.0
  6   0.963210       3.0      26.0
  7   0.769306       6.0      25.0
  8   0.440867       9.0      26.0
  9   0.929054       4.0      25.0
  10  0.033989       6.0      29.0
  11  0.927164       1.0      27.0
1 0   0.219389       7.0      24.0
  1   0.613668       4.0      25.0
  2   0.087804       7.0      21.0
  3   0.995796       7.0      20.0
  4   0.771184       6.0      20.0
  5   0.534013       3.0      26.0
  6   0.831465       3.0      20.0
  7   0.863216       6.0      27.0
  8   0.683494       5.0      20.0
  9   0.995828       5.0      27.0
  10  0.431961       1.0      24.0
  11  0.005792       7.0      22.0
2 0   0.219878       4.0      26.0
  1   0.297455       7.0      24.0
  2   0.647589       8.0      28.0
  3   0.972401       9.0      22.0
  4   0.609236       9.0      28.0
  5   0.414977       4.0      22.0
  6   0.272910       1.0      24.0
  7   0.234230       1.0      25.0
  8   0.147175       2.0      28.0
  9   0.102641       1.0      28.0
  10  0.316599       5.0      20.0
  11  0.420905       8.0      20.0
3 0   0.865145       5.0      28.0
  1   0.480571       3.0      25.0
  2   0.275608       9.0      24.0
  3   0.385029       9.0      28.0
  4   0.229359       1.0      20.0
  5   0.398263       8.0      22.0
  6   0.516401       4.0      20.0
  7   0.938618       9.0      29.0
  8   0.471717       8.0      28.0
  9   0.629520       3.0      28.0
  10  0.759610       2.0      20.0
  11  0.041509       5.0      20.0

# 给index标上名字，便于等一下groupby

In [20]:
indexes = df.index
indexes

MultiIndex(levels=[[0, 1, 2, 3], [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]],
           labels=[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3], [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]])

In [27]:
# 以这样的方式可以命名
indexes.set_names(['listing', 'month'])

MultiIndex(levels=[[0, 1, 2, 3], [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]],
           labels=[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3], [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]],
           names=[u'listing', u'month'])

In [30]:
# 所以：
df.index = df.index.set_names(['listing', 'month'])

In [31]:
df

               feature1  feature2  feature3
listing month
0       0      0.870154       9.0      24.0
        1      0.656261       1.0      27.0
        2      0.297759       6.0      21.0
        3      0.693777       5.0      27.0
        4      0.939945       4.0      24.0
        5      0.876682       2.0      21.0
        6      0.963210       3.0      26.0
        7      0.769306       6.0      25.0
        8      0.440867       9.0      26.0
        9      0.929054       4.0      25.0
        10     0.033989       6.0      29.0
        11     0.927164       1.0      27.0
1       0      0.219389       7.0      24.0
        1      0.613668       4.0      25.0
        2      0.087804       7.0      21.0
        3      0.995796       7.0      20.0
        4      0.771184       6.0      20.0
        5      0.534013       3.0      26.0
        6      0.831465       3.0      20.0
        7      0.863216       6.0      27.0
        8      0.683494       5.0      20.0
        9      0.995828       5.0      27.0
        10     0.431961       1.0      24.0
        11     0.005792       7.0      22.0
2       0      0.219878       4.0      26.0
        1      0.297455       7.0      24.0
        2      0.647589       8.0      28.0
        3      0.972401       9.0      22.0
        4      0.609236       9.0      28.0
        5      0.414977       4.0      22.0
        6      0.272910       1.0      24.0
        7      0.234230       1.0      25.0
        8      0.147175       2.0      28.0
        9      0.102641       1.0      28.0
        10     0.316599       5.0      20.0
        11     0.420905       8.0      20.0
3       0      0.865145       5.0      28.0
        1      0.480571       3.0      25.0
        2      0.275608       9.0      24.0
        3      0.385029       9.0      28.0
        4      0.229359       1.0      20.0
        5      0.398263       8.0      22.0
        6      0.516401       4.0      20.0
        7      0.938618       9.0      29.0
        8      0.471717       8.0      28.0
        9      0.629520       3.0      28.0
        10     0.759610       2.0      20.0
        11     0.041509       5.0      20.0

# 万事俱备，聚合吧

In [40]:
# 参数level必须要， groupby的第一个变量是 by，是指列名
df.groupby(level='listing').count()
#每个listing的每个变量有12个月的维度， 所以count为12

         feature1  feature2  feature3
listing
0              12        12        12
1              12        12        12
2              12        12        12
3              12        12        12

In [41]:
df.groupby(level='month').count()
#同理，4个listing

       feature1  feature2  feature3
month
0             4         4         4
1             4         4         4
2             4         4         4
3             4         4         4
4             4         4         4
5             4         4         4
6             4         4         4
7             4         4         4
8             4         4         4
9             4         4         4
10            4         4         4
11            4         4         4

# 其他 sum、 average等都类似，参照groupby之后的操作

## 下面是按条件聚合

In [70]:
# 每个listing，第二个变量，大于8的月数
result = df[df['feature2'] > 8].groupby(level='listing').apply(len)
print(type(result))
result

# 结果对不对，自己去上面数

<class 'pandas.core.series.Series'>

listing
0    2
2    2
3    3
dtype: int64

# 那么，如何把没有的这个条件的listing补齐？
> 原因：`df[df['feature2'] > 8]` 这里就已经把不符合条件的行删掉了，因此listing==1的行都不满足，都被删掉

# 如果期待的应该是listing长度不变，缺失值补na？

In [72]:
listing_index = df.index.get_level_values('listing').unique()
listing_index

Int64Index([0, 1, 2, 3], dtype='int64', name=u'listing')

In [73]:
result_pad = pd.Series(result, index=listing_index)
result_pad

listing
0    2.0
1    NaN
2    2.0
3    3.0
dtype: float64

In [75]:
# 4维... n维，都可以用类似方式

In [76]:
# Happy pandas